# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  PORT: 8888
  # SHELL: '{{if eq .OS "Windows_NT"}}pwsh{{end}}'

tasks:
  do: # just do it
    deps: [stop, run-background, test, cleanup]

  stop:
    desc: Stop processes running on port {{.PORT}}
    cmds:
      - pwsh -c Write-Host "[LOG] Force stopping any processes running on {{.PORT}}..."
      - pwsh -File ./stop-server.ps1 -Port {{.PORT}}

  list:
    desc: List all available tasks
    cmds:
      - task -l

  default:
    desc: Default task (shows help)
    cmds:
      - task --list

  create-env:
    desc: Create micromamba environment
    cmds:
      - pwsh -c wsl micromamba.exe create -n jl -f ./build-environment.without-ext.yml -y
    # sources: Task will only run if build-environment.without-ext.yml changes
    sources:
      - build-environment.without-ext.yml

  create-ext:
    desc: build extension
    cmds:
      - pwsh -c Write-Host "building extension"
      - pwsh -c 'wsl micromamba.exe run -n jl uv pip install . --reinstall'
    sources:
      - 'js/src/**'

  # rebuilds and runs the server
  run:
    desc: run the server (foreground - blocks)
    deps: [stop, create-env, create-ext]
    cmds:
      - pwsh -c 'Write-Host "[WARN] prefixing commands with wsl for windows environment"'
      - pwsh -File ./start-server.ps1 -Port {{.PORT}}
      - pwsh -c 'start-sleep -seconds 5'
      # - pwsh -File ./Test-ConsoleErrors.ps1

  run-background:
    desc: Run server in background
    deps: [stop, create-env, create-ext]
    cmds:
      - pwsh -c 'Write-Host "[WARN] prefixing commands with wsl for windows environment"'
      - pwsh -File ./start-server.ps1 -Port {{.PORT}}
      - pwsh -c 'Start-Sleep -Seconds 5'

  test:
    cmds:
      - pwsh -File ./Test-ConsoleErrors.ps1

  cleanup:
    desc: Stop server after tests
    cmds:
      - pwsh -File ./stop-server.ps1 -Port {{.PORT}}
